run:
  timeout: 10m
  go: "1.23"
  mod: readonly

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - govet
    - cyclop
    - errcheck
    - errname
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - funlen
    - gocritic
    - gomnd
    - goimports
    - gofmt
    - nestif
linters-settings:
  funlen:
    lines: -1
    statements: 60
  cyclop:
    max-complexity: 15
    skip-tests: true
